'use client';
import {useEffect,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';
type Cat=any; type Match=any;
const arr=(s:string)=>s.split(',').map(x=>x.trim()).filter(Boolean);
const Icon=({name}:{name:string})=>{const paths:any={grid:<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,plus:<><path d="M12 5v14M5 12h14"/></>,pin:<><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,check:<path d="m5 12 4 4L19 6"/>,external:<><path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h5"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>};return <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name]}</svg>}
export default function Home(){
 const [cats,setCats]=useState<Cat[]>([]),[jobs,setJobs]=useState<Match[]>([]),[selected,setSelected]=useState(''),[drawer,setDrawer]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[loading,setLoading]=useState(true),[userEmail,setUserEmail]=useState('');
 const load=async()=>{setLoading(true);const c=await fetch('/api/categories').then(r=>r.json());setCats(Array.isArray(c)?c:[]);const j=await fetch('/api/jobs'+(selected?`?category=${selected}`:'')).then(r=>r.json());setJobs(Array.isArray(j)?j:[]);setLoading(false)};
 useEffect(()=>{load()},[selected]);
 useEffect(()=>{createBrowserSupabase().auth.getUser().then(({data})=>setUserEmail(data.user?.email||''))},[]);
 const logout=async()=>{await createBrowserSupabase().auth.signOut();window.location.href='/login'};
 const create=async(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget),type=String(f.get('type'));const body={name:f.get('name'),slug:String(f.get('name')).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''),type,enabled:true,role_keywords:arr(String(f.get('roles'))),hidden_keywords:arr(String(f.get('hidden'))),exclude_keywords:arr(String(f.get('exclude'))),locations:arr(String(f.get('locations'))),max_experience_years:Number(f.get('exp')||2),salary_min_monthly:Number(f.get('salaryMin')||0)||null,salary_max_monthly:Number(f.get('salaryMax')||0)||null,stipend_min_monthly:Number(f.get('stipendMin')||0)||null,stipend_max_monthly:Number(f.get('stipendMax')||0)||null,require_paid:type==='internship',require_official_verification:type==='government',source_kinds:arr(String(f.get('sources'))),alert_threshold:Number(f.get('threshold')||70)};const r=await fetch('/api/categories',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)alert((await r.json()).error);else{setDrawer(false);load()}};
 return <main className="shell"><header className="top"><div className="brandMark"><span className="logo"><Icon name="search"/></span><div><h1>JobRadar South</h1><p>Verified fresher opportunities in cybersecurity, networking and cloud infrastructure</p></div></div><div className="actions"><button className="btn secondary" onClick={()=>setSettingsOpen(true)}><Icon name="bell"/>Notifications</button><button className="btn secondary" onClick={()=>setSelected('')}><Icon name="grid"/>All matches</button><button className="btn" onClick={()=>setDrawer(true)}><Icon name="plus"/>New category</button><div className="account"><span className="accountText"><b>{userEmail||'Signed in'}</b><small>Google account</small></span><button className="signout" onClick={logout}>Sign out</button></div></div></header>
 <div className="grid"><aside className="panel sidebar"><div className="eyebrow">RESEARCH CATEGORIES</div><p className="muted">Scheduled research follows the rules defined in each category.</p>{cats.map(c=><button key={c.id} className={'cat '+(selected===c.id?'active':'')} onClick={()=>setSelected(c.id)}><span>{c.name}</span><small>{c.locations?.slice(0,2).join(' · ')} · {c.alert_threshold}%+</small></button>)}</aside>
 <section className="panel content"><div className="sectionHead"><div><div className="eyebrow">{selected?'CATEGORY RESULTS':'CURRENT RESULTS'}</div><h2>{selected?(cats.find(c=>c.id===selected)?.name||'Category'):'Best current matches'}</h2><p className="muted">Official and ATS application links are preferred. Compensation is shown only when disclosed.</p></div><span className="count">{jobs.length} matches</span></div>{loading?<div className="empty">Loading current matches…</div>:jobs.length===0?<div className="empty">No verified matches yet. The scheduled collector will populate this view.</div>:<div className="jobs">{jobs.map((m,i)=>{const j=m.job;return <article className="job" key={j.id||i}><div className="jobTop"><span className="score">{m.score}% match</span>{j.official_verified&&<span className="verified"><Icon name="check"/>Verified</span>}</div><h3>{j.title}</h3><div className="company">{j.company}</div><div className="location"><Icon name="pin"/>{j.location||'Location not disclosed'}</div><div className="badges"><span className="badge">{m.category?.name}</span>{m.ai_review?.consensus?.providers?.length>0&&<span className="badge">AI reviewed · {m.ai_review.consensus.confidence}%</span>}<span className="badge">{j.salary_min_monthly?`₹${j.salary_min_monthly.toLocaleString()}/month`:'Salary not disclosed'}</span></div><p className="reason">{(m.reasons||[]).slice(0,3).join(' · ')}</p><div className="links">{j.apply_verified&&j.apply_url?<a className="applyLink" href={j.apply_url} target="_blank" rel="noreferrer">Apply now <Icon name="external"/></a>:<span className="muted small">Direct application link pending verification</span>}{j.notification_url&&<a className="textLink" href={j.notification_url} target="_blank" rel="noreferrer">Official notification <Icon name="external"/></a>}</div></article>})}</div>}</section></div>
 {drawer&&<div className="overlay" onClick={()=>setDrawer(false)}><div className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><div className="eyebrow">RESEARCH RULES</div><h2>Create category</h2></div><button className="close" onClick={()=>setDrawer(false)}>×</button></div><p className="muted">New categories are automatically included in subsequent scheduled research runs.</p><form className="form" onSubmit={create}><label>Name<input required name="name" placeholder="DevOps Fresher"/></label><label>Type<select name="type"><option value="custom">Custom</option><option value="government">Government / PSU</option><option value="startup">Startup</option><option value="entry_level">Entry level</option><option value="internship">Paid internship</option></select></label><label>Primary role keywords<textarea required name="roles" placeholder="network engineer, cloud support, security analyst"/></label><label>Adjacent / hidden titles<textarea name="hidden" placeholder="systems engineer, technical support"/></label><label>Exclude<textarea name="exclude" placeholder="senior, lead, 5+ years"/></label><label>Locations<input required name="locations" defaultValue="Chennai, Tamil Nadu, Bengaluru, Bangalore, Kerala"/></label><div className="split"><label>Max experience<input name="exp" type="number" defaultValue="2" step="0.5"/></label><label>Alert score<input name="threshold" type="number" defaultValue="70"/></label></div><div className="split"><label>Salary minimum<input name="salaryMin" type="number"/></label><label>Salary target<input name="salaryMax" type="number"/></label></div><div className="split"><label>Stipend minimum<input name="stipendMin" type="number"/></label><label>Stipend target<input name="stipendMax" type="number"/></label></div><label>Source kinds<input name="sources" defaultValue="ats, company, community"/></label><button className="btn wide">Create category</button></form></div></div>}
 {settingsOpen&&<div className="overlay" onClick={()=>setSettingsOpen(false)}><div className="drawer compact" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><div className="eyebrow">ALERT DELIVERY</div><h2>Notifications</h2></div><button className="close" onClick={()=>setSettingsOpen(false)}>×</button></div><p className="muted">JobRadar uses only the free-first channels below. Credentials stay in GitHub Actions secrets, not in the browser.</p><div className="channels"><div className="channel"><b>ntfy</b><span>Primary instant push notification</span></div><div className="channel"><b>Telegram</b><span>Searchable job alert history</span></div><div className="channel"><b>Email</b><span>Reliable archive and fallback</span></div></div><div className="notice">Configure delivery credentials in GitHub repository secrets. See SETUP.md for exact names and steps.</div></div></div>}
 </main>
}
