'use client';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type Row=Record<string,any>;
const presets=['Chennai','Tamil Nadu','Bengaluru','Kerala','Kochi','Coimbatore','Thiruvananthapuram','Remote'];
const csv=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
const svg:Record<string,React.ReactNode>={
 search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
 play:<><circle cx="12" cy="12" r="9"/><path d="m10 8 6 4-6 4Z"/></>,
 settings:<><circle cx="12" cy="12" r="3"/><path d="M4 12h2m12 0h2M12 4v2m0 12v2M6.3 6.3l1.4 1.4m8.6 8.6 1.4 1.4m0-11.4-1.4 1.4M7.7 16.3l-1.4 1.4"/></>,
 briefcase:<><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 7V4h6v3M3 12h18"/></>,
 file:<><path d="M6 2h8l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></>,
 upload:<><path d="M12 16V4M7 9l5-5 5 5"/><path d="M4 15v5h16v-5"/></>,
 pin:<><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/></>,
 external:<><path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h5"/></>,
 check:<path d="m5 12 4 4L19 6"/>,bookmark:<path d="M6 3h12v18l-6-4-6 4z"/>,trash:<><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,sync:<><path d="M20 7h-5V2M4 17h5v5"/><path d="M19 11a7 7 0 0 0-12-5L4 9M5 13a7 7 0 0 0 12 5l3-3"/></>
};
function Icon({n}:{n:string}){return <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{svg[n]}</svg>}

export default function Home(){
 const [cats,setCats]=useState<Row[]>([]),[jobs,setJobs]=useState<Row[]>([]),[selected,setSelected]=useState('');
 const [prefs,setPrefs]=useState<Row|null>(null),[notify,setNotify]=useState<Row|null>(null),[resumes,setResumes]=useState<Row[]>([]),[apps,setApps]=useState<Row[]>([]),[saved,setSaved]=useState<Set<string>>(new Set());
 const [email,setEmail]=useState(''),[status,setStatus]=useState<Row|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[saving,setSaving]=useState(false);
 const [settings,setSettings]=useState(false),[tab,setTab]=useState<'resume'|'preferences'|'auto'|'notifications'>('resume'),[appOpen,setAppOpen]=useState(false);
 const active=useMemo(()=>resumes.find(x=>x.is_active)||resumes.find(x=>x.id===prefs?.active_resume_id)||null,[resumes,prefs]);
 const completeness=useMemo(()=>{if(!active)return 0;const p=active.parsed_json||{};const x=[p.full_name,p.email,p.phone,(active.skills||[]).length,(active.education||[]).length,(prefs?.locations||[]).length,(prefs?.target_roles||[]).length];return Math.round(x.filter(Boolean).length/x.length*100)},[active,prefs]);
 const loadJobs=async()=>{const q=selected?`?category_id=${encodeURIComponent(selected)}`:'';const [c,j,s]=await Promise.all([fetch('/api/categories').then(r=>r.json()),fetch('/api/jobs'+q).then(r=>r.json()),fetch('/api/status').then(r=>r.json()).catch(()=>null)]);setCats(Array.isArray(c)?c:[]);setJobs(Array.isArray(j)?j:[]);if(s&&!s.error)setStatus(s)};
 const loadProfile=async()=>{const [r,p,n,a,sv]=await Promise.all([fetch('/api/resumes').then(x=>x.json()),fetch('/api/preferences').then(x=>x.json()),fetch('/api/settings').then(x=>x.json()),fetch('/api/applications').then(x=>x.json()),fetch('/api/saved').then(x=>x.json())]);setResumes(Array.isArray(r)?r:[]);if(p&&!p.error)setPrefs(p);if(n&&!n.error)setNotify(n);setApps(Array.isArray(a)?a:[]);setSaved(new Set((Array.isArray(sv)?sv:[]).map((x:any)=>x.job_id)))};
 useEffect(()=>{loadJobs()},[selected]);useEffect(()=>{loadProfile();createBrowserSupabase().auth.getUser().then(({data})=>setEmail(data.user?.email||''))},[]);
 const run=async(mode='research')=>{setBusy(true);const r=await fetch('/api/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode})});const d=await r.json().catch(()=>({}));setBusy(false);setNotice(r.ok?(mode==='research'?'Research queued.':'Notification test queued.'):d.error||'Unable to start workflow')};
 const save=async()=>{if(!prefs||!notify)return;setSaving(true);const [a,b]=await Promise.all([fetch('/api/preferences',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(prefs)}),fetch('/api/settings',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({ntfy_enabled:!!notify.ntfy_enabled,telegram_enabled:!!notify.telegram_enabled,email_enabled:!!notify.email_enabled,minimum_score:Number(notify.minimum_score||65)})})]);setSaving(false);setNotice(a.ok&&b.ok?'Changes saved and synced.':'Some settings could not be saved.');if(a.ok&&b.ok)loadProfile()};
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setUploading(true);const fd=new FormData();fd.append('file',f);const r=await fetch('/api/resumes',{method:'POST',body:fd});const d=await r.json();setUploading(false);e.target.value='';setNotice(r.ok?'Resume uploaded and profile extracted.':d.error||'Resume upload failed');if(r.ok)loadProfile()};
 const activate=async(id:string)=>{await fetch('/api/resumes',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,is_active:true})});setNotice('Active resume changed. Run research to refresh matches.');loadProfile()};
 const delResume=async(id:string)=>{if(!confirm('Delete this resume?'))return;await fetch(`/api/resumes?id=${id}`,{method:'DELETE'});loadProfile()};
 const toggleLoc=(x:string)=>setPrefs((p:any)=>({...p,locations:(p?.locations||[]).includes(x)?p.locations.filter((y:string)=>y!==x):[...(p?.locations||[]),x]}));
 const toggleSave=async(id:string)=>{if(saved.has(id)){await fetch(`/api/saved?job_id=${id}`,{method:'DELETE'});setSaved(new Set([...saved].filter(x=>x!==id)))}else{await fetch('/api/saved',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({job_id:id})});setSaved(new Set([...saved,id]))}};
 const markApplied=async(m:Row)=>{await fetch('/api/applications',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({job_id:m.job.id,resume_id:active?.id,status:'applied_manual',method:'manual',score:m.score,apply_url:m.job.apply_url})});setNotice('Application added to tracker.');loadProfile()};
 const logout=async()=>{await createBrowserSupabase().auth.signOut();location.href='/login'};
 const chosen=cats.find(c=>c.id===selected);
 return <main className="shell">
  <header className="top"><div className="brandMark"><span className="logo"><svg viewBox="0 0 32 32"><circle cx="16" cy="16" r="10"/><circle cx="16" cy="16" r="4"/><path d="M16 16 25 9"/><circle className="logoDot" cx="25" cy="9" r="2"/></svg></span><div><h1>JobRadar South</h1><p>Resume-driven fresher job research for networking, cybersecurity and cloud infrastructure</p></div></div><div className="actions"><button className="btn secondary" disabled={busy} onClick={()=>run()}><Icon n="play"/>{busy?'Starting…':'Run research'}</button><button className="btn secondary" onClick={()=>setAppOpen(true)}><Icon n="briefcase"/>Applications</button><button className="btn secondary" onClick={()=>setSettings(true)}><Icon n="settings"/>Settings</button><div className="account"><span className="accountText"><b>{email}</b><small>Google account</small></span><button className="signout" onClick={logout}>Sign out</button></div></div></header>
  {notice&&<div className="flash">{notice}</div>}
  {status&&<div className="statusbar"><div><Icon n="sync"/>Latest run: {status.started_at?new Date(status.started_at).toLocaleString():'—'}</div><div className="statusStats"><span>{status.status}</span><span>{status.discovered||0} discovered</span><span>{status.verified||0} verified</span><span>{status.matched||0} matched</span><span>{status.alerted||0} alerted</span></div></div>}
  <section className="grid"><aside className="sideStack"><div className="panel profileCard"><div className="eyebrow">ACTIVE PROFILE</div>{active?<><div className="resumeTitle"><Icon n="file"/><div><b>{active.name}</b><small>{(active.skills||[]).slice(0,3).join(' · ')||'Resume parsed'}</small></div></div><div className="progress"><span style={{width:`${completeness}%`}}/></div><p className="muted compactText">{completeness}% profile completeness</p><button className="textButton" onClick={()=>{setTab('resume');setSettings(true)}}>Manage resumes</button></>:<><p className="muted compactText">Upload a resume to personalize research and matching.</p><button className="btn secondary wide" onClick={()=>{setTab('resume');setSettings(true)}}>Add resume</button></>}</div><div className="panel sidebar"><div className="eyebrow">RESEARCH CATEGORIES</div><button className={!selected?'cat active':'cat'} onClick={()=>setSelected('')}><span>All matches</span><small>Every enabled category</small></button>{cats.map(c=><button key={c.id} className={selected===c.id?'cat active':'cat'} onClick={()=>setSelected(c.id)}><span>{c.name}</span><small>{(c.locations||[]).slice(0,2).join(' · ')} · {c.alert_threshold}%+</small></button>)}</div></aside>
   <section className="panel content"><div className="sectionHead"><div><div className="eyebrow">VERIFIED RESULTS</div><h2>{chosen?.name||'All matches'}</h2><p className="muted">Scores combine strict role relevance, selected locations and your active resume.</p></div><span className="count">{jobs.length} matches</span></div><div className="jobs">{jobs.length===0?<div className="empty">No verified matches yet. Save your profile and run research.</div>:jobs.map(m=>{const j=m.job||{};return <article className="job" key={`${m.job_id}-${m.category_id}`}><div className="jobTop"><span className="score">{m.score}% match{m.resume_score!=null?` · resume ${m.resume_score}%`:''}</span><div className="jobActions"><span className="verified"><Icon n="check"/>Verified</span><button className={'iconButton '+(saved.has(j.id)?'selected':'')} onClick={()=>toggleSave(j.id)} title="Save job"><Icon n="bookmark"/></button></div></div><h3>{j.title}</h3><div className="company">{j.company}</div><div className="location"><Icon n="pin"/>{j.location||'Location not disclosed'}</div><div className="badges"><span className="badge">{m.category?.name}</span>{j.salary_min_monthly?<span className="badge">₹{Number(j.salary_min_monthly).toLocaleString()}/month</span>:j.stipend_monthly?<span className="badge">₹{Number(j.stipend_monthly).toLocaleString()} stipend</span>:<span className="badge">Compensation not disclosed</span>}</div><p className="reason">{[...(m.resume_reasons||[]),...(m.reasons||[])].slice(0,3).join(' · ')}</p>{(m.skill_gaps||[]).length>0&&<div className="gapLine"><b>Skill gaps</b>{m.skill_gaps.slice(0,5).join(', ')}</div>}<div className="links">{j.apply_url&&<a className="applyLink" href={j.apply_url} target="_blank" rel="noreferrer">Apply now <Icon n="external"/></a>}{j.notification_url&&<a className="textLink" href={j.notification_url} target="_blank" rel="noreferrer">Official notification <Icon n="external"/></a>}<button className="textLink buttonLink" onClick={()=>markApplied(m)}>Mark applied</button></div></article>})}</div></section></section>
  {settings&&<div className="overlay" onClick={()=>setSettings(false)}><div className="drawer settingsDrawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><div className="eyebrow">SYNCED PROFILE</div><h2>Settings</h2></div><button className="close" onClick={()=>setSettings(false)}>×</button></div><div className="settingsTabs"><button className={tab==='resume'?'active':''} onClick={()=>setTab('resume')}>Resumes</button><button className={tab==='preferences'?'active':''} onClick={()=>setTab('preferences')}>Job preferences</button><button className={tab==='auto'?'active':''} onClick={()=>setTab('auto')}>Auto apply</button><button className={tab==='notifications'?'active':''} onClick={()=>setTab('notifications')}>Notifications</button></div>
   {tab==='resume'&&<div className="settingsBody"><div className="uploadBox"><Icon n="upload"/><div><b>Upload resume</b><small>PDF, DOCX or TXT · max 10 MB</small></div><label className="btn secondary uploadButton">{uploading?'Extracting…':'Choose file'}<input type="file" accept=".pdf,.docx,.txt" disabled={uploading} onChange={upload}/></label></div><div className="resumeList">{resumes.map(r=><div className={'resumeRow '+(r.is_active?'active':'')} key={r.id}><div className="resumeIcon"><Icon n="file"/></div><div className="resumeMeta"><b>{r.name}</b><small>{r.original_filename} · {Math.round(r.size_bytes/1024)} KB</small><div className="miniTags">{(r.skills||[]).slice(0,5).map((x:string)=><span key={x}>{x}</span>)}</div></div><div className="resumeControls">{r.is_active?<span className="activeBadge">Active</span>:<button className="textButton" onClick={()=>activate(r.id)}>Use this</button>}<button className="iconButton" onClick={()=>delResume(r.id)}><Icon n="trash"/></button></div></div>)}</div>{active&&<div className="parsedPanel"><b>Extracted profile</b><div className="detailGrid"><span>Name<strong>{active.parsed_json?.full_name||'Not found'}</strong></span><span>Email<strong>{active.parsed_json?.email||'Not found'}</strong></span><span>Experience<strong>{active.experience_years!=null?`${active.experience_years} years`:'Not stated'}</strong></span><span>Skills<strong>{(active.skills||[]).length}</strong></span></div></div>}</div>}
   {tab==='preferences'&&prefs&&<div className="settingsBody form"><label>Preferred locations<div className="chips">{presets.map(x=><button type="button" key={x} className={(prefs.locations||[]).includes(x)?'chip selected':'chip'} onClick={()=>toggleLoc(x)}>{x}</button>)}</div></label><label>Locations<input value={(prefs.locations||[]).join(', ')} onChange={e=>setPrefs({...prefs,locations:csv(e.target.value)})}/></label><label>Target roles<textarea value={(prefs.target_roles||[]).join(', ')} onChange={e=>setPrefs({...prefs,target_roles:csv(e.target.value)})}/></label><label>Exclude terms<textarea value={(prefs.excluded_terms||[]).join(', ')} onChange={e=>setPrefs({...prefs,excluded_terms:csv(e.target.value)})}/></label><div className="split"><label>Max experience<input type="number" step=".5" value={prefs.max_experience_years??2} onChange={e=>setPrefs({...prefs,max_experience_years:Number(e.target.value)})}/></label><label>Minimum salary<input type="number" value={prefs.salary_min_monthly??20000} onChange={e=>setPrefs({...prefs,salary_min_monthly:Number(e.target.value)})}/></label></div><div className="split"><label>Salary target<input type="number" value={prefs.salary_target_monthly??27000} onChange={e=>setPrefs({...prefs,salary_target_monthly:Number(e.target.value)})}/></label><label>Minimum stipend<input type="number" value={prefs.stipend_min_monthly??10000} onChange={e=>setPrefs({...prefs,stipend_min_monthly:Number(e.target.value)})}/></label></div><label className="toggleRow"><span><b>Include remote</b><small>Allow verified remote roles</small></span><input type="checkbox" checked={!!prefs.allow_remote} onChange={e=>setPrefs({...prefs,allow_remote:e.target.checked})}/></label><label className="toggleRow"><span><b>Include hybrid</b><small>Allow hybrid roles in selected locations</small></span><input type="checkbox" checked={!!prefs.allow_hybrid} onChange={e=>setPrefs({...prefs,allow_hybrid:e.target.checked})}/></label></div>}
   {tab==='auto'&&prefs&&<div className="settingsBody"><div className="notice strongNotice"><b>Safe auto apply is beta.</b><span>Government jobs are always manual. Captchas and unknown required questions stop for review.</span></div><label className="toggleRow"><span><b>Queue high-confidence matches</b><small>Use active resume above your threshold</small></span><input type="checkbox" checked={!!prefs.auto_apply_enabled} onChange={e=>setPrefs({...prefs,auto_apply_enabled:e.target.checked})}/></label><label className="toggleRow"><span><b>Allow final auto-submit</b><small>Only supported Greenhouse, Lever and Ashby forms</small></span><input type="checkbox" checked={!!prefs.auto_submit_enabled} onChange={e=>setPrefs({...prefs,auto_submit_enabled:e.target.checked})}/></label><label className="fieldLabel">Auto-apply threshold<input type="number" min="80" max="100" value={prefs.auto_apply_threshold??95} onChange={e=>setPrefs({...prefs,auto_apply_threshold:Number(e.target.value)})}/></label><div className="form"><div className="eyebrow">APPLICATION PROFILE</div>{['current_city','phone','linkedin_url','github_url','portfolio_url'].map(k=><label key={k}>{k.replaceAll('_',' ')}<input value={prefs.application_answers?.[k]||((k==='phone'?active?.parsed_json?.phone:k==='linkedin_url'?active?.parsed_json?.linkedin_url:k==='github_url'?active?.parsed_json?.github_url:'')||'')} onChange={e=>setPrefs({...prefs,application_answers:{...(prefs.application_answers||{}),[k]:e.target.value}})}/></label>)}</div></div>}
   {tab==='notifications'&&notify&&<div className="settingsBody">{[['ntfy_enabled','ntfy','Instant Android push'],['telegram_enabled','Telegram','Searchable alert history'],['email_enabled','Email','Archive and fallback']].map(([k,t,d])=><label className="toggleRow" key={k}><span><b>{t}</b><small>{d}</small></span><input type="checkbox" checked={!!notify[k]} onChange={e=>setNotify({...notify,[k]:e.target.checked})}/></label>)}<label className="fieldLabel">Minimum notification score<input type="number" min="0" max="100" value={notify.minimum_score??65} onChange={e=>setNotify({...notify,minimum_score:Number(e.target.value)})}/></label><button className="btn secondary wide" disabled={busy} onClick={()=>run('test-notifications')}><Icon n="bell"/>Send test notifications</button></div>}
   <div className="saveBar"><div className="syncState"><Icon n="sync"/><span>Changes sync to Supabase and are used by scheduled research.</span></div><button className="btn" disabled={saving} onClick={save}>{saving?'Saving…':'Save changes'}</button></div></div></div>}
  {appOpen&&<div className="overlay" onClick={()=>setAppOpen(false)}><div className="drawer applicationsDrawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><div className="eyebrow">APPLICATION TRACKER</div><h2>Applications</h2></div><button className="close" onClick={()=>setAppOpen(false)}>×</button></div><div className="applicationList">{apps.length===0?<div className="empty">No applications tracked yet.</div>:apps.map(a=><div className="applicationRow" key={a.id}><div><b>{a.job?.title||'Job'}</b><span>{a.job?.company}</span><small>{a.resume?.name?`Resume: ${a.resume.name}`:'No resume'} · score {a.score??'—'}%</small></div><select value={a.status} onChange={async e=>{await fetch('/api/applications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:a.id,status:e.target.value})});loadProfile()}}>{['saved','queued','review_required','submitted','applied_manual','interview','offer','rejected','withdrawn'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></div>)}</div></div></div>}
 </main>
}
