import {NextResponse} from 'next/server';
import {Document,Packer,Paragraph,TextRun,HeadingLevel,AlignmentType} from 'docx';
import {admin} from '@/lib/supabase';
import {getAuthorizedUser} from '@/lib/auth';
export const runtime='nodejs';
const a=(v:any)=>Array.isArray(v)?v.map(String).filter(Boolean):[];
const safe=(s:string)=>String(s||'resume').replace(/[^a-z0-9._-]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,80)||'resume';
const heading=(t:string)=>new Paragraph({text:t,heading:HeadingLevel.HEADING_2,spacing:{before:180,after:70}});
const bullets=(rows:string[])=>rows.map(x=>new Paragraph({text:x,bullet:{level:0},spacing:{after:45}}));
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const auth=await getAuthorizedUser();if(auth.status!==200)return NextResponse.json({error:'Unauthorized'},{status:auth.status});const {id}=await params;const {data:r}=await admin().from('generated_resumes').select('*').eq('id',id).eq('user_id',auth.user!.id).maybeSingle();if(!r)return NextResponse.json({error:'Resume not found'},{status:404});const c=r.content_json||{};const children:any[]=[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:String(c.name||'Candidate'),bold:true,size:34})]}),new Paragraph({alignment:AlignmentType.CENTER,text:String(c.contact||''),spacing:{after:120}}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:String(c.headline||''),bold:true,size:24})],spacing:{after:160}})];if(c.summary){children.push(heading('PROFESSIONAL SUMMARY'),new Paragraph({text:String(c.summary)}))}if(a(c.skills).length){children.push(heading('VERIFIED SKILLS'),new Paragraph({text:a(c.skills).join(' • ')}))}if(a(c.learning_skills).length){children.push(heading('CURRENTLY LEARNING FOR THIS ROLE'),new Paragraph({text:a(c.learning_skills).join(' • ')}),new Paragraph({children:[new TextRun({text:'These technologies are learning targets for this application and are not presented as prior professional proficiency.',italics:true})],spacing:{after:70}}))}if(a(c.experience_bullets).length){children.push(heading('EXPERIENCE'),...bullets(a(c.experience_bullets)))}if(a(c.project_bullets).length){children.push(heading('PROJECTS'),...bullets(a(c.project_bullets)))}if(a(c.education).length){children.push(heading('EDUCATION'),...a(c.education).map(x=>new Paragraph({text:x})))}if(a(c.certifications).length){children.push(heading('CERTIFICATIONS'),...a(c.certifications).map(x=>new Paragraph({text:x})))}const doc=new Document({styles:{default:{document:{run:{font:'Arial',size:21},paragraph:{spacing:{after:70,line:260}}}}},sections:[{properties:{page:{margin:{top:720,right:720,bottom:720,left:720}}},children}]});const buffer=await Packer.toBuffer(doc);return new NextResponse(new Uint8Array(buffer),{headers:{'content-type':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','content-disposition':`attachment; filename="${safe(r.title)}.docx"`,'cache-control':'private, no-store'}})}
